services:
  - type: web
    name: zrntv-api
    env: node
    region: oregon
    buildCommand: npm install && npm start
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TMDB_KEY
        # Replace with your TMDB API key or set in Render dashboard
        # Get one free at: https://www.themoviedb.org/settings/api
        value: c138886a68189d4f50a36bd5fe53e588
    autoDeploy: true
    repo: https://github.com/zrncrblln/zrntv
